### ISSUE TITLE
[head inertia data added]

### ISSUE THREAD

**Issue by Lurentz** [ADVRHumanoids/iit-cogimon-ros-pkg#5]

**Comment by Lurentz** [comment]
daie

**Comment by EnricoMingo** [comment]
I have updated the model in the ```lorenzo_prova``` brench which now @FrancescoRuscelli  is tensting as well in simulation. Due to the form of the head I had to remove any collision for the hokuyo (maybe I can add the visualization indeed). Furthermore: in the data provided it was missing the transformation from the torso frame to the head frame, I assumed the one I was using before. 

Last, the transformation provided in the documentation are the inverse of the one needed to compile the urdf, so I had to compute them using matlab, ini the next part you should provide the inverse transformation (if we move from frame A to frame B I need the pose of B wrt A).

**Comment by EnricoMingo** [comment]
Merged to master
